cc_library(
    name="headers",
    visibility  = ["//visibility:public"],
    hdrs = [
        "fun/Arity.h",
        "fun/ConstantFunction.h",
        "fun/IFunction.h",
        "fun/IFunctionGenerator.h",
    ],
)