cc_library(
    name="headers",
    visibility  = ["//visibility:public"],
    hdrs = [
        "Registry.h",
        "fun/Arity.h",
        "fun/ConstantFunction.h",
        "fun/CoordinateFunction.h",
        "fun/IFunction.h",
        "fun/IFunctionGenerator.h",
        "fun/NegateFunction.h",
        "fun/RoundFunction.h",
        "fun/TrigFunction.h",
    ],
)