cc_binary(
    name = "pretty-picture",
    srcs = [
        "main.cc",
    ],
    copts = [
    ],
    deps = [
        "//include",
        "//src/pp",
        "@boost//:optional",
        "@libbmp//:main",
        "@lodepng//:main",
    ]
)